### ISSUE TITLE
Instruction needs to be fixed

### ISSUE THREAD

**Issue by jm2292236** [learn-co-curriculum/phase-3-orms-mapping-classes-to-database-tables#12]
### Canvas Link

https://my.learn.co/courses/382/assignments/18367?module_item_id=42163

### Concern

Try this out by running ruby bin/pry and running this code in the Pry session

### Additional Context

This is about the "Mapping Ruby Classes to a Database" assignment.

### Suggested Changes

The text should say:
Try this out by running ruby **bin/run** and running this code in the Pry session...

**Comment by lizbur10** [comment]
Hi @jm2292236 ! Thanks for bringing this to our attention - the error has been fixed. 💙
