### ISSUE TITLE
Too much content 

### ISSUE THREAD

**Issue by erichegonzales** [learn-co-curriculum/phase-3-orms-mapping-classes-to-database-tables#13]
### Canvas Link

https://learning.flatironschool.com/courses/5208/assignments/199378?module_item_id=451158

### Concern

A lot of content for one section, overwhelming,should split it into smaller sections so students can digest the information better

**Comment by lizbur10** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in
upcoming releases of this curriculum.

As always, thanks for contributing! 💙
