### ISSUE TITLE
this doesn't run unless you also run bundle install on some systems (mine)

### ISSUE THREAD

**Issue by hariseldon27** [learn-co-curriculum/phase-3-orms-mapping-classes-to-database-tables#4]
### Canvas Link

https://learning.flatironschool.com/courses/4987/assignments/169333?module_item_id=367034

### Concern

yes we are learning ruby, but as a 'code-along' that says all the code is in place it's pretty lame that we are given code that doesn't work without a reminder to run the install for a language we've had less than seven days with.

**Comment by AlveeM** [comment]
Hello, and thank you for spotting this issue and providing feedback.

We have updated the GitHub repo and believe your issue to have been resolved. Note, however, that if you are working in Canvas the changes may not show up there, but they will for future students.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not! We appreciate your support!

If you do not believe that this issue has been addressed, please re-open this issue. 💙
