### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by Leavingvalhalla** [learn-co-curriculum/phase-3-orms-mapping-classes-to-database-tables#6]
### Canvas Link

https://learning.flatironschool.com/courses/4980/assignments/169132?module_item_id=366646

### Concern

On line 157 in the README (but also on the webpage) you have the explanation of a heredoc, but you say that it takes a word meaning "end of document" twice, instead of the first one saying a word that means "start of document".

**Comment by professor-ben** [comment]
Hello,

The heredoc syntax actually works quite similarly to an HTML tag ( <p> </p> and so on ). the open and close should both use that same special end of document word so that the interpreter knows that it is one block that starts at the first and stops at the second.

Thanks,
Ben

**Comment by Leavingvalhalla** [comment]
Hey Ben, thanks for getting back to me. I may have done a poor job explaining what I was seeing, or maybe I just still don't understand your response. Here's the bit I was referring to:
![Screen Shot 2022-04-16 at 9 57 30 AM](https://user-images.githubusercontent.com/92550332/163684313-5e498003-5ce5-49ea-b3cc-ce0f1ee38ea9.png)

I was referring to the fact that it says 'special word meaning "End of Document"' twice, when I would expect one of them to read 'special word meaning "Start of Document"'. If I'm wrong, I apologize for taking up your time.
